/**
 * Generated by scripts/sync-counts.ts. Do not edit.
 *
 * The landing page quotes these. Generating them means the sentence cannot
 * outlive the fact, which is how "70 tests" and "3 payouts" survived past being
 * true.
 */

export const TEST_COUNTS = {
  cairo: 81,
  typescript: 71,
  total: 152,
} as const;
