/**
 * Count the tests and write them where the site can read them.
 *
 * The landing page quotes a test count. It was typed by hand, said 70, and was
 * right by luck at the moment it was typed. A number in a sentence is a claim,
 * and this repository's characteristic failure is claims that were true once.
 *
 *   node scripts/sync-counts.ts            write it
 *   node scripts/sync-counts.ts --check    fail if it would change (CI)
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "apps/web/app/lib/counts.ts");

const tracked = execFileSync("git", ["ls-files"], { cwd: ROOT, encoding: "utf8" })
  .split("\n")
  .filter(Boolean);

const read = (p: string) => readFileSync(resolve(ROOT, p), "utf8");

const cairo = tracked
  .filter((f) => f.startsWith("contracts/tests/") && f.endsWith(".cairo"))
  .reduce((n, f) => n + (read(f).match(/^\s*#\[test\]/gm) ?? []).length, 0);

const typescript = tracked
  .filter((f) => f.endsWith(".test.ts"))
  .reduce((n, f) => n + (read(f).match(/^\s*(?:test|it)\(/gm) ?? []).length, 0);

const rendered = `/**
 * Generated by scripts/sync-counts.ts. Do not edit.
 *
 * The landing page quotes these. Generating them means the sentence cannot
 * outlive the fact, which is how "70 tests" and "3 payouts" survived past being
 * true.
 */

export const TEST_COUNTS = {
  cairo: ${cairo},
  typescript: ${typescript},
  total: ${cairo + typescript},
} as const;
`;

const current = (() => {
  try {
    return readFileSync(OUT, "utf8");
  } catch {
    return "";
  }
})();

if (process.argv.includes("--check")) {
  if (current === rendered) {
    console.log(`counts in sync: ${cairo} Cairo + ${typescript} TypeScript = ${cairo + typescript}`);
    process.exit(0);
  }
  console.error("apps/web/app/lib/counts.ts is stale. Run: node scripts/sync-counts.ts");
  process.exit(1);
}

writeFileSync(OUT, rendered);
console.log(`counts written: ${cairo} Cairo + ${typescript} TypeScript = ${cairo + typescript}`);
