//! Ballot identity derivation.
//!
//! A vote is a private transfer into a per-choice receiving identity, so every
//! voter needs to know where to send — and needs to be able to check that
//! address for themselves rather than trusting whoever runs the front end.
//!
//! Both halves are derived from public inputs. The salt comes from the proposal
//! and the choice; the address is then Starknet's ordinary contract-address
//! formula over the DAO's account class and master public key. The DAO derives
//! the same accounts off-chain from the secret behind that public key, which is
//! how the tally service ends up holding their viewing keys.
//!
//! The formula is reproduced here rather than imported because the core library
//! exposes no pure function for it. `tests/test_ballot.cairo` pins the output
//! against vectors generated by starknet.js — if those ever disagree, ballots
//! would be sent to addresses nobody controls, so treat that test as load
//! bearing.

use core::pedersen::pedersen;
use core::poseidon::poseidon_hash_span;
use starknet::ContractAddress;

/// Domain separator, so a ballot salt can never collide with a hash computed
/// for some other purpose over the same numbers.
pub const BALLOT_TAG: felt252 = 'APERTURE_BALLOT:V1';

/// `'STARKNET_CONTRACT_ADDRESS'` as a felt.
pub const CONTRACT_ADDRESS_PREFIX: felt252 = 'STARKNET_CONTRACT_ADDRESS';

/// Addresses are `2**251 - 256` at most; the raw hash is reduced into range.
pub const ADDR_BOUND: u256 = 0x7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00;

/// Ballot choices. The discriminant is part of the salt, so the order of these
/// variants is consensus-critical — appending is safe, reordering is not.
#[derive(Serde, Copy, Drop, PartialEq, Debug)]
pub enum Choice {
    For,
    Against,
    Abstain,
}

pub fn choice_index(choice: Choice) -> felt252 {
    match choice {
        Choice::For => 0,
        Choice::Against => 1,
        Choice::Abstain => 2,
    }
}

/// Deterministic salt for one proposal/choice pair.
pub fn ballot_salt(proposal_id: u64, choice: Choice) -> felt252 {
    poseidon_hash_span([BALLOT_TAG, proposal_id.into(), choice_index(choice)].span())
}

/// Pedersen chain over the elements, terminated by the count — the standard
/// Starknet array hash.
fn hash_on_elements(elements: Span<felt252>) -> felt252 {
    let mut acc: felt252 = 0;
    let mut i = 0;
    while i != elements.len() {
        acc = pedersen(acc, *elements.at(i));
        i += 1;
    }
    pedersen(acc, elements.len().into())
}

/// Starknet's contract-address formula, for a deployment from the zero address.
///
/// This is one `hash_on_elements` over all five inputs — not a nested pedersen
/// chain. The difference is the leading zero and the trailing element count,
/// and getting it wrong yields a plausible-looking address that is simply not
/// the one the sequencer will deploy to.
pub fn compute_address(
    salt: felt252, class_hash: felt252, constructor_calldata: Span<felt252>,
) -> ContractAddress {
    let calldata_hash = hash_on_elements(constructor_calldata);
    let raw = hash_on_elements(
        [CONTRACT_ADDRESS_PREFIX, 0, salt, class_hash, calldata_hash].span(),
    );
    let bounded: u256 = Into::<felt252, u256>::into(raw) % ADDR_BOUND;
    let felt: felt252 = bounded.try_into().expect('ADDRESS_OUT_OF_RANGE');
    felt.try_into().expect('INVALID_ADDRESS')
}

/// The receiving identity for one choice on one proposal.
pub fn ballot_address(
    proposal_id: u64, choice: Choice, class_hash: felt252, master_public_key: felt252,
) -> ContractAddress {
    compute_address(ballot_salt(proposal_id, choice), class_hash, [master_public_key].span())
}
